---
abstract: 'collect a bundle of modules into one'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Collector
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Syntax::Collector:
    file: lib/Syntax/Collector.pm
    version: 0.006
  Syntax::Collector::Collection:
    file: lib/Syntax/Collector.pm
    version: 0.006
requires:
  Exporter::Tiny: 0
  Module::Runtime: 0
  perl: 5.006001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Syntax-Collector/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Syntax-Collector
  homepage: https://metacpan.org/release/Syntax-Collector
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-syntax-collector
version: 0.006
